fix: reduce panic and better error msg
dioxus-community/dioxus-i18n pull request #8
Opened 2024-12-11 21:16 UTC by mrxiaozhuox

I don't think the program should panic directly when the corresponding information cannot be found. My initial solution is to return the msg directly.

### More Improvement Plans

1. Introduce tracing, and log an error message to alert developers while returning the msg.

2. If you must panic, please refer to my handling solution for the pattern: provide more specific information.

2024-12-11 21:20 UTC, mrxiaozhuox commented
I just checked #7, and it seems to add specific msg information. This is also a better solution (although I still think it shouldn't panic).

2024-12-14 22:44 UTC, marc2332 requested changes

2024-12-14 22:44 UTC, marc2332 commented on src/use_i18n.rs
> +            .unwrap_or_else(|| panic!("Failed to get the message: `{}` pattern.", msg));
Minor suggestion!
```suggestion
        let Some(message) = bundle.get_message(msg) else {
            return msg.to_string();
        };
        let pattern = message
            .value()
            .unwrap_or_else(|| panic!("Failed to get the message: `{}` pattern.", msg));
```

2024-12-14 22:44 UTC, marc2332 commented
> I just checked #7, and it seems to add specific msg information. This is also a better solution (although I still think it shouldn't panic).

Its a fair point, returning the message id in case of 404 sounds good to me

2024-12-22 15:58 UTC, marc2332 commented on src/use_i18n.rs
> +            .unwrap_or_else(|| panic!("Failed to get the message: `{}` pattern.", msg));
This suggestion still stands @mrxiaozhuox

2025-01-04 22:55 UTC, nigeleke commented
@marc2332 the try_methods change I've mentioned [elsewhere](https://github.com/nigeleke/dioxus-i18n/tree/feature/try_methods) enables the library's end-user to make decisions on how / where to manage panics.
I'll do a PR for it as soon as we've completed the "graceful fallbacks PR"

2025-01-05 18:02 UTC, marc2332 commented
> @marc2332 the try_methods change I've mentioned [elsewhere](https://github.com/nigeleke/dioxus-i18n/tree/feature/try_methods) enables the library's end-user to make decisions on how / where to manage panics. I'll do a PR for it as soon as we've completed the "graceful fallbacks PR"

Should we merge this, then?

2025-01-05 20:27 UTC, nigeleke commented
> > @marc2332 the try_methods change I've mentioned [elsewhere](https://github.com/nigeleke/dioxus-i18n/tree/feature/try_methods) enables the library's end-user to make decisions on how / where to manage panics. I'll do a PR for it as soon as we've completed the "graceful fallbacks PR"
> 
> Should we merge this, then?

It's probably not worth it, but I will make sure the "better error message" part of it is included in the try_methods PR.

2025-01-06 14:33 UTC, marc2332 commented
Closing this in favor of @nigeleke's PR then, hope its ok @mrxiaozhuox ❤️

2025-01-06 14:33 UTC, closed without merging